version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node Api service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000
      DB_URL: mongodb://mongo_db:27017
      DB_NAME: NetinfoMetaverse
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}